apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation-dev
  labels:
    app: geolocation-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: geolocation-dev
  template:
    metadata:
      labels:
        app: geolocation-dev
    spec:
      containers:
      - name: geolocation-dev
        image: hadask/geolocation:1.3
        ports:
        - containerPort: 8080
      # - name: mongodb
      #   image: mongo
      #   ports:
      #   - name: mongodbport
      #     containerPort: 27017
      #     protocol: TCP
